//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_inc_lab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_inc_lab()
        {
            this.causas_basicas = new HashSet<causas_basicas>();
            this.causas_inmediatas = new HashSet<causas_inmediatas>();
            this.compromisos = new HashSet<compromisos>();
            this.consultas = new HashSet<consultas>();
            this.fotos_accidente = new HashSet<fotos_accidente>();
            this.testigos = new HashSet<testigos>();
        }
    
        public int id_acc_lab { get; set; }
        public Nullable<int> tipo_acci_inci { get; set; }
        public string grado { get; set; }
        public Nullable<System.DateTime> fecha_inv { get; set; }
        public Nullable<System.DateTime> hora_inv { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<System.DateTime> fecha_acc { get; set; }
        public Nullable<System.DateTime> hora_acc { get; set; }
        public Nullable<int> id_ips { get; set; }
        public Nullable<int> id_tipo_acc { get; set; }
        public Nullable<int> id_sitio_acc { get; set; }
        public Nullable<System.DateTime> tiempo_prev_lab { get; set; }
        public string breve_desc { get; set; }
        public string desc_hechos { get; set; }
        public Nullable<int> id_puesto_trabajo { get; set; }
        public Nullable<int> id_agente_lesion { get; set; }
        public Nullable<int> id_causa_accidente { get; set; }
        public Nullable<int> id_parte_cuerpo { get; set; }
        public Nullable<int> id_forma_acc { get; set; }
        public string eventos_similar { get; set; }
        public string cuenta_matriz_riesgos { get; set; }
        public string contemplado_matriz { get; set; }
        public string personas_presenciaron_accidente { get; set; }
        public string situaciones_noclaras { get; set; }
        public string encargado_sst { get; set; }
        public string integrante_copasst { get; set; }
        public string brigadista { get; set; }
        public string jefe_inmediato { get; set; }
        public string prof_salud_ocu { get; set; }
        public string documento_escaneado { get; set; }
        public string num_consultas { get; set; }
        public string frecuencia_consulta { get; set; }
        public string documento_comunicado { get; set; }
    
        public virtual agente_lesion agente_lesion { get; set; }
        public virtual area area { get; set; }
        public virtual causa_accidente causa_accidente { get; set; }
        public virtual forma_accidente forma_accidente { get; set; }
        public virtual ips ips { get; set; }
        public virtual parte_cuerpo parte_cuerpo { get; set; }
        public virtual puesto_trabajo puesto_trabajo { get; set; }
        public virtual sitio_accidente sitio_accidente { get; set; }
        public virtual tipo_accidente tipo_accidente { get; set; }
        public virtual trabajador trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<causas_basicas> causas_basicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<causas_inmediatas> causas_inmediatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compromisos> compromisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultas> consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fotos_accidente> fotos_accidente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testigos> testigos { get; set; }
    }
}
