//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class compromisos
    {
        public int id_compromiso { get; set; }
        public string controles { get; set; }
        public Nullable<System.DateTime> fecha_implementacion { get; set; }
        public string fuente { get; set; }
        public string medio { get; set; }
        public string persona { get; set; }
        public string responsable { get; set; }
        public int id_acc_lab { get; set; }
    
        public virtual acc_inc_lab acc_inc_lab { get; set; }
    }
}
