//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultas
    {
        public int id_consulta { get; set; }
        public int id_acc_lab { get; set; }
        public string tipo { get; set; }
        public string servicio_medico { get; set; }
        public string fecha { get; set; }
        public string medico { get; set; }
        public string diagnostico { get; set; }
        public string sug_trat { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual acc_inc_lab acc_inc_lab { get; set; }
    }
}
