//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrupoLiEntities : DbContext
    {
        public GrupoLiEntities()
            : base("name=GrupoLiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acc_inc_lab> acc_inc_lab { get; set; }
        public virtual DbSet<afp> afp { get; set; }
        public virtual DbSet<agente_lesion> agente_lesion { get; set; }
        public virtual DbSet<alarmas> alarmas { get; set; }
        public virtual DbSet<anexos> anexos { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<arp> arp { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<causa_accidente> causa_accidente { get; set; }
        public virtual DbSet<causas_basicas> causas_basicas { get; set; }
        public virtual DbSet<causas_inmediatas> causas_inmediatas { get; set; }
        public virtual DbSet<ccf> ccf { get; set; }
        public virtual DbSet<codigo_ciiu> codigo_ciiu { get; set; }
        public virtual DbSet<compromisos> compromisos { get; set; }
        public virtual DbSet<consultas> consultas { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<desc_socio> desc_socio { get; set; }
        public virtual DbSet<division> division { get; set; }
        public virtual DbSet<empleos_anteriores> empleos_anteriores { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<empresa_itemdivision> empresa_itemdivision { get; set; }
        public virtual DbSet<enfermedad> enfermedad { get; set; }
        public virtual DbSet<eps> eps { get; set; }
        public virtual DbSet<estatus> estatus { get; set; }
        public virtual DbSet<estatus_obligacion> estatus_obligacion { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<factor_riesgo> factor_riesgo { get; set; }
        public virtual DbSet<forma_accidente> forma_accidente { get; set; }
        public virtual DbSet<fotos_accidente> fotos_accidente { get; set; }
        public virtual DbSet<frecuencia_control> frecuencia_control { get; set; }
        public virtual DbSet<gestion_laboral> gestion_laboral { get; set; }
        public virtual DbSet<historia_clinica_ocupacional> historia_clinica_ocupacional { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<ips> ips { get; set; }
        public virtual DbSet<items_division> items_division { get; set; }
        public virtual DbSet<matrizRiesgo_enfermedadLaboral> matrizRiesgo_enfermedadLaboral { get; set; }
        public virtual DbSet<matrizRiesgo_factorRiesgo> matrizRiesgo_factorRiesgo { get; set; }
        public virtual DbSet<matrizRiesgo_tipoRiesgo> matrizRiesgo_tipoRiesgo { get; set; }
        public virtual DbSet<medidas> medidas { get; set; }
        public virtual DbSet<medidas_sucursal> medidas_sucursal { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<normas> normas { get; set; }
        public virtual DbSet<normas_sucursal> normas_sucursal { get; set; }
        public virtual DbSet<obligacion> obligacion { get; set; }
        public virtual DbSet<parte_cuerpo> parte_cuerpo { get; set; }
        public virtual DbSet<plan_mapa> plan_mapa { get; set; }
        public virtual DbSet<plan_trabajo> plan_trabajo { get; set; }
        public virtual DbSet<prioridad> prioridad { get; set; }
        public virtual DbSet<puesto_trabajo> puesto_trabajo { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<riesgos> riesgos { get; set; }
        public virtual DbSet<riesgos_item> riesgos_item { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sistemas> sistemas { get; set; }
        public virtual DbSet<sitio_accidente> sitio_accidente { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<testigos> testigos { get; set; }
        public virtual DbSet<tipo_accidente> tipo_accidente { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<tipo_examen> tipo_examen { get; set; }
        public virtual DbSet<tipo_gestion> tipo_gestion { get; set; }
        public virtual DbSet<tipo_riesgo> tipo_riesgo { get; set; }
        public virtual DbSet<trabajador> trabajador { get; set; }
        public virtual DbSet<trabajador_estatus> trabajador_estatus { get; set; }
        public virtual DbSet<trabajador_gestion> trabajador_gestion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
