//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrupoLiEntities1 : DbContext
    {
        public GrupoLiEntities1()
            : base("name=GrupoLiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Afp> Tbl_Afp { get; set; }
        public virtual DbSet<Tbl_Alarma> Tbl_Alarma { get; set; }
        public virtual DbSet<Tbl_Area> Tbl_Area { get; set; }
        public virtual DbSet<Tbl_Arl> Tbl_Arl { get; set; }
        public virtual DbSet<Tbl_At_it_el_pa> Tbl_At_it_el_pa { get; set; }
        public virtual DbSet<Tbl_AutoEvaluacion> Tbl_AutoEvaluacion { get; set; }
        public virtual DbSet<Tbl_Brigada_emergencia> Tbl_Brigada_emergencia { get; set; }
        public virtual DbSet<Tbl_Categoria> Tbl_Categoria { get; set; }
        public virtual DbSet<Tbl_Ccf> Tbl_Ccf { get; set; }
        public virtual DbSet<Tbl_ClaseCiiu> Tbl_ClaseCiiu { get; set; }
        public virtual DbSet<Tbl_Cno> Tbl_Cno { get; set; }
        public virtual DbSet<Tbl_Consulta> Tbl_Consulta { get; set; }
        public virtual DbSet<Tbl_Departamento> Tbl_Departamento { get; set; }
        public virtual DbSet<Tbl_Desc_socio> Tbl_Desc_socio { get; set; }
        public virtual DbSet<Tbl_DivisionCiiu> Tbl_DivisionCiiu { get; set; }
        public virtual DbSet<Tbl_Documento> Tbl_Documento { get; set; }
        public virtual DbSet<Tbl_Empleo_anterior> Tbl_Empleo_anterior { get; set; }
        public virtual DbSet<Tbl_Empresa> Tbl_Empresa { get; set; }
        public virtual DbSet<Tbl_Empresa_itemdivision> Tbl_Empresa_itemdivision { get; set; }
        public virtual DbSet<Tbl_Encuesta_politica> Tbl_Encuesta_politica { get; set; }
        public virtual DbSet<Tbl_Enfermedad> Tbl_Enfermedad { get; set; }
        public virtual DbSet<Tbl_EnfermedadLaboral> Tbl_EnfermedadLaboral { get; set; }
        public virtual DbSet<Tbl_Epp> Tbl_Epp { get; set; }
        public virtual DbSet<Tbl_Eps> Tbl_Eps { get; set; }
        public virtual DbSet<Tbl_Estatus> Tbl_Estatus { get; set; }
        public virtual DbSet<Tbl_Evaluacion_riesgo> Tbl_Evaluacion_riesgo { get; set; }
        public virtual DbSet<Tbl_Evento> Tbl_Evento { get; set; }
        public virtual DbSet<Tbl_Extintor> Tbl_Extintor { get; set; }
        public virtual DbSet<Tbl_Factor_identificacion> Tbl_Factor_identificacion { get; set; }
        public virtual DbSet<Tbl_Factor_riesgo> Tbl_Factor_riesgo { get; set; }
        public virtual DbSet<Tbl_Frecuencia_control> Tbl_Frecuencia_control { get; set; }
        public virtual DbSet<Tbl_Gestion_laboral> Tbl_Gestion_laboral { get; set; }
        public virtual DbSet<Tbl_GrupoCiiu> Tbl_GrupoCiiu { get; set; }
        public virtual DbSet<Tbl_Historia_clinica_ocupacional> Tbl_Historia_clinica_ocupacional { get; set; }
        public virtual DbSet<Tbl_Horario> Tbl_Horario { get; set; }
        public virtual DbSet<Tbl_Identificacion_peligro> Tbl_Identificacion_peligro { get; set; }
        public virtual DbSet<Tbl_Identificacion_puesto> Tbl_Identificacion_puesto { get; set; }
        public virtual DbSet<Tbl_Investigacion_ac_in> Tbl_Investigacion_ac_in { get; set; }
        public virtual DbSet<Tbl_Ips> Tbl_Ips { get; set; }
        public virtual DbSet<Tbl_Lista_actividad> Tbl_Lista_actividad { get; set; }
        public virtual DbSet<Tbl_Matriz_Acc_Prev_Corr> Tbl_Matriz_Acc_Prev_Corr { get; set; }
        public virtual DbSet<Tbl_Matriz_responsabilidad> Tbl_Matriz_responsabilidad { get; set; }
        public virtual DbSet<Tbl_MatrizEpp> Tbl_MatrizEpp { get; set; }
        public virtual DbSet<Tbl_Medida> Tbl_Medida { get; set; }
        public virtual DbSet<Tbl_Medida_sucursal> Tbl_Medida_sucursal { get; set; }
        public virtual DbSet<Tbl_Municipio> Tbl_Municipio { get; set; }
        public virtual DbSet<Tbl_Norma> Tbl_Norma { get; set; }
        public virtual DbSet<Tbl_Norma_claseciiu> Tbl_Norma_claseciiu { get; set; }
        public virtual DbSet<Tbl_Norma_sucursal> Tbl_Norma_sucursal { get; set; }
        public virtual DbSet<Tbl_Obligacion> Tbl_Obligacion { get; set; }
        public virtual DbSet<Tbl_Perfil_cargo> Tbl_Perfil_cargo { get; set; }
        public virtual DbSet<Tbl_Perfil_medico> Tbl_Perfil_medico { get; set; }
        public virtual DbSet<Tbl_Plan> Tbl_Plan { get; set; }
        public virtual DbSet<Tbl_Plan_trabajo> Tbl_Plan_trabajo { get; set; }
        public virtual DbSet<Tbl_Politica_sst> Tbl_Politica_sst { get; set; }
        public virtual DbSet<Tbl_Pregunta> Tbl_Pregunta { get; set; }
        public virtual DbSet<Tbl_Procedimiento_comunicacion> Tbl_Procedimiento_comunicacion { get; set; }
        public virtual DbSet<Tbl_Puesto_trabajo> Tbl_Puesto_trabajo { get; set; }
        public virtual DbSet<Tbl_Puesto_trabajo_epp> Tbl_Puesto_trabajo_epp { get; set; }
        public virtual DbSet<Tbl_Region> Tbl_Region { get; set; }
        public virtual DbSet<Tbl_Respuesta> Tbl_Respuesta { get; set; }
        public virtual DbSet<Tbl_Riesgos_item> Tbl_Riesgos_item { get; set; }
        public virtual DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public virtual DbSet<Tbl_SeccionCiiu> Tbl_SeccionCiiu { get; set; }
        public virtual DbSet<Tbl_Simulacro> Tbl_Simulacro { get; set; }
        public virtual DbSet<Tbl_Sistema> Tbl_Sistema { get; set; }
        public virtual DbSet<Tbl_Soporte> Tbl_Soporte { get; set; }
        public virtual DbSet<Tbl_Sucursal> Tbl_Sucursal { get; set; }
        public virtual DbSet<Tbl_Tipo_documento> Tbl_Tipo_documento { get; set; }
        public virtual DbSet<Tbl_Tipo_epp> Tbl_Tipo_epp { get; set; }
        public virtual DbSet<Tbl_Tipo_evento> Tbl_Tipo_evento { get; set; }
        public virtual DbSet<Tbl_Tipo_examen> Tbl_Tipo_examen { get; set; }
        public virtual DbSet<Tbl_Tipo_riesgo> Tbl_Tipo_riesgo { get; set; }
        public virtual DbSet<Tbl_Trabajador> Tbl_Trabajador { get; set; }
        public virtual DbSet<Tbl_Trabajador_estatus> Tbl_Trabajador_estatus { get; set; }
        public virtual DbSet<Tbl_Trabajador_gestion> Tbl_Trabajador_gestion { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
        public virtual DbSet<Tbl_Senalizacion> Tbl_Senalizacion { get; set; }
    }
}
