//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class obligacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public obligacion()
        {
            this.anexos = new HashSet<anexos>();
        }
    
        public int id_obligacion { get; set; }
        public Nullable<int> id_medida_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public int id_categorias { get; set; }
        public int id_prioridad { get; set; }
        public int id_frecuencia_con { get; set; }
        public string descripcion { get; set; }
        public string acciones { get; set; }
        public int id_estatus_obl { get; set; }
        public Nullable<int> id_riesgo { get; set; }
        public Nullable<int> id_actividad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anexos> anexos { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual estatus_obligacion estatus_obligacion { get; set; }
        public virtual frecuencia_control frecuencia_control { get; set; }
        public virtual medidas_sucursal medidas_sucursal { get; set; }
        public virtual plan_trabajo plan_trabajo { get; set; }
        public virtual prioridad prioridad { get; set; }
        public virtual riesgos riesgos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
