//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public riesgos()
        {
            this.obligacion = new HashSet<obligacion>();
        }
    
        public int id_riesgos { get; set; }
        public Nullable<int> id_puesto_trabajo { get; set; }
        public Nullable<System.DateTime> fecha_eva { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public string identificacion_riesgo { get; set; }
        public string probabilidad { get; set; }
        public string severidad { get; set; }
        public string valor_riesgo { get; set; }
        public Nullable<int> id_prioridad { get; set; }
        public string medidas_fuente { get; set; }
        public string estatus_med_fue { get; set; }
        public string medidas_ambiente { get; set; }
        public string estatus_med_amb { get; set; }
        public string medidas_trabajador { get; set; }
        public string estatus_med_trab { get; set; }
        public string estatus { get; set; }
        public Nullable<int> id_factor_riesgo { get; set; }
        public string nombre_responsable { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string consecuencia { get; set; }
        public Nullable<int> matriz_riesgo { get; set; }
        public Nullable<int> porc_estatus { get; set; }
    
        public virtual factor_riesgo factor_riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obligacion> obligacion { get; set; }
        public virtual prioridad prioridad { get; set; }
        public virtual puesto_trabajo puesto_trabajo { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
