//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sucursal()
        {
            this.area = new HashSet<area>();
            this.normas_sucursal = new HashSet<normas_sucursal>();
            this.plan_mapa = new HashSet<plan_mapa>();
            this.riesgos = new HashSet<riesgos>();
        }
    
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_municpio { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string direccion { get; set; }
        public Nullable<int> sede_principal { get; set; }
        public string representante { get; set; }
        public string movil { get; set; }
        public string fijo { get; set; }
        public Nullable<int> actividad_ppal { get; set; }
        public Nullable<int> actividad_sec { get; set; }
        public Nullable<int> actividad_otra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<area> area { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual municipio municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<normas_sucursal> normas_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_mapa> plan_mapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riesgos> riesgos { get; set; }
    }
}
