//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Soporte
    {
        public int id_soporte { get; set; }
        public string url { get; set; }
        public Nullable<int> id_tabla { get; set; }
        public string tabla { get; set; }
    
        public virtual Tbl_At_it_el_pa Tbl_At_it_el_pa { get; set; }
        public virtual Tbl_Documento Tbl_Documento { get; set; }
        public virtual Tbl_Obligacion Tbl_Obligacion { get; set; }
    }
}
