//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_At_it_el_pa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_At_it_el_pa()
        {
            this.Tbl_Consulta = new HashSet<Tbl_Consulta>();
            this.Tbl_Investigacion_ac_in = new HashSet<Tbl_Investigacion_ac_in>();
            this.Tbl_Soporte = new HashSet<Tbl_Soporte>();
        }
    
        public int id_at_it_el_pa { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<int> id_puesto { get; set; }
        public string sitio { get; set; }
        public string descripcion { get; set; }
        public string condiciones_inseguras { get; set; }
        public string actos_inseguros { get; set; }
        public string factores_inseguros { get; set; }
        public string factores_personales { get; set; }
        public string reporte_accidente { get; set; }
        public string documento_escaneado { get; set; }
        public string documento_comunicado { get; set; }
        public Nullable<int> num_consultas { get; set; }
        public string frecuencia_consultas { get; set; }
        public string tipo_evento { get; set; }
        public Nullable<System.DateTime> fecha_muerte { get; set; }
        public Nullable<int> dias_incapacidad { get; set; }
        public Nullable<int> dias_cargados { get; set; }
        public Nullable<int> dias_perdidos_ausencia { get; set; }
        public string dias_no_perdidos { get; set; }
        public string tipo_enfermedad { get; set; }
        public Nullable<System.DateTime> fecha_accidente { get; set; }
        public Nullable<System.DateTime> hora_accidente { get; set; }
        public Nullable<int> dias_perdidos_restingido { get; set; }
    
        public virtual Tbl_Area Tbl_Area { get; set; }
        public virtual Tbl_Puesto_trabajo Tbl_Puesto_trabajo { get; set; }
        public virtual Tbl_Trabajador Tbl_Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Consulta> Tbl_Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Investigacion_ac_in> Tbl_Investigacion_ac_in { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Soporte> Tbl_Soporte { get; set; }
    }
}
