//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empleo_anterior
    {
        public int id_empleos_ant { get; set; }
        public string empresa { get; set; }
        public string area { get; set; }
        public string cargo { get; set; }
        public string años { get; set; }
        public string meses { get; set; }
        public string enfermedades { get; set; }
        public Nullable<int> id_desc_socio { get; set; }
    
        public virtual Tbl_Desc_socio Tbl_Desc_socio { get; set; }
    }
}
