//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Brigada_emergencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Brigada_emergencia()
        {
            this.Tbl_Procedimiento_comunicacion = new HashSet<Tbl_Procedimiento_comunicacion>();
        }
    
        public int id_brigada { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string perfiles { get; set; }
        public string func_brigadistas { get; set; }
        public string brigada_comunicacion { get; set; }
        public string dir_emergencia_int { get; set; }
        public string brigada_prim_aux { get; set; }
        public string brigada_incendio { get; set; }
        public string brigada_evacuacion { get; set; }
    
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Procedimiento_comunicacion> Tbl_Procedimiento_comunicacion { get; set; }
    }
}
