//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DivisionCiiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_DivisionCiiu()
        {
            this.Tbl_GrupoCiiu = new HashSet<Tbl_GrupoCiiu>();
        }
    
        public int id_division { get; set; }
        public Nullable<int> id_seccion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual Tbl_SeccionCiiu Tbl_SeccionCiiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_GrupoCiiu> Tbl_GrupoCiiu { get; set; }
    }
}
