//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Extintor
    {
        public int id_extintor { get; set; }
        public string serial_extintor { get; set; }
        public Nullable<System.DateTime> fecha_ultima_recarga { get; set; }
        public Nullable<System.DateTime> fecha_proxima_recarga { get; set; }
        public string peso { get; set; }
        public string presion { get; set; }
        public string tipo_extintor { get; set; }
        public string nombre_empresa { get; set; }
        public Nullable<int> id_area { get; set; }
    
        public virtual Tbl_Area Tbl_Area { get; set; }
    }
}
