//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Matriz_Acc_Prev_Corr
    {
        public int id { get; set; }
        public string origen { get; set; }
        public Nullable<System.DateTime> fecha_reporte { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_area { get; set; }
        public string actividad { get; set; }
        public string prioridad { get; set; }
        public string accion { get; set; }
        public string responsable { get; set; }
        public Nullable<System.DateTime> fecha_propuesta { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
    
        public virtual Tbl_Area Tbl_Area { get; set; }
    }
}
