//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Empresa()
        {
            this.Tbl_AutoEvaluacion = new HashSet<Tbl_AutoEvaluacion>();
            this.Tbl_Categoria = new HashSet<Tbl_Categoria>();
            this.Tbl_Empresa_itemdivision = new HashSet<Tbl_Empresa_itemdivision>();
            this.Tbl_Epp = new HashSet<Tbl_Epp>();
            this.Tbl_Estatus = new HashSet<Tbl_Estatus>();
            this.Tbl_Horario = new HashSet<Tbl_Horario>();
            this.Tbl_Perfil_cargo = new HashSet<Tbl_Perfil_cargo>();
            this.Tbl_Politica_sst = new HashSet<Tbl_Politica_sst>();
            this.Tbl_Rol = new HashSet<Tbl_Rol>();
            this.Tbl_Sucursal = new HashSet<Tbl_Sucursal>();
        }
    
        public int id_empresa { get; set; }
        public string nombre { get; set; }
        public string CodEmpresa { get; set; }
        public string nit { get; set; }
        public string email { get; set; }
        public string representante { get; set; }
        public string movil { get; set; }
        public string fijo { get; set; }
        public string logo_url { get; set; }
        public Nullable<int> id_arl { get; set; }
        public Nullable<int> jornada { get; set; }
        public string clase_riesgo { get; set; }
        public string tipo_material { get; set; }
        public string dependencias_adm { get; set; }
        public string dependencias_no_adm { get; set; }
        public Nullable<int> personas_transito { get; set; }
        public string vias_acceso { get; set; }
        public string salida_emergencia { get; set; }
        public string senalizacion { get; set; }
    
        public virtual Tbl_Arl Tbl_Arl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AutoEvaluacion> Tbl_AutoEvaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Categoria> Tbl_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Empresa_itemdivision> Tbl_Empresa_itemdivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Epp> Tbl_Epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Estatus> Tbl_Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Horario> Tbl_Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Perfil_cargo> Tbl_Perfil_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Politica_sst> Tbl_Politica_sst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Rol> Tbl_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sucursal> Tbl_Sucursal { get; set; }
    }
}
