//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Norma_sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Norma_sucursal()
        {
            this.Tbl_Medida_sucursal = new HashSet<Tbl_Medida_sucursal>();
        }
    
        public int id_normas_sucursal { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_normas { get; set; }
        public Nullable<int> estatus_norma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Medida_sucursal> Tbl_Medida_sucursal { get; set; }
        public virtual Tbl_Norma Tbl_Norma { get; set; }
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
