//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Obligacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Obligacion()
        {
            this.Tbl_Soporte = new HashSet<Tbl_Soporte>();
        }
    
        public int id_obligacion { get; set; }
        public Nullable<int> id_medida_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public int id_categorias { get; set; }
        public string prioridad { get; set; }
        public int id_frecuencia_con { get; set; }
        public string descripcion { get; set; }
        public string acciones { get; set; }
        public string estatus_obl { get; set; }
        public Nullable<int> id_identificacion_peligro { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_trabajador { get; set; }
    
        public virtual Tbl_Categoria Tbl_Categoria { get; set; }
        public virtual Tbl_Frecuencia_control Tbl_Frecuencia_control { get; set; }
        public virtual Tbl_Identificacion_peligro Tbl_Identificacion_peligro { get; set; }
        public virtual Tbl_Medida_sucursal Tbl_Medida_sucursal { get; set; }
        public virtual Tbl_Plan_trabajo Tbl_Plan_trabajo { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Soporte> Tbl_Soporte { get; set; }
    }
}
