//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Identificacion_puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Identificacion_puesto()
        {
            this.Tbl_Evaluacion_riesgo = new HashSet<Tbl_Evaluacion_riesgo>();
        }
    
        public int id_ide_puesto { get; set; }
        public Nullable<int> id_identificacion { get; set; }
        public Nullable<int> id_puesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Evaluacion_riesgo> Tbl_Evaluacion_riesgo { get; set; }
        public virtual Tbl_Identificacion_peligro Tbl_Identificacion_peligro { get; set; }
        public virtual Tbl_Puesto_trabajo Tbl_Puesto_trabajo { get; set; }
    }
}
