//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Norma_claseciiu
    {
        public int id_normas_clase { get; set; }
        public Nullable<int> id_normas { get; set; }
        public Nullable<int> id_clase_ciiu { get; set; }
    
        public virtual Tbl_ClaseCiiu Tbl_ClaseCiiu { get; set; }
        public virtual Tbl_Norma Tbl_Norma { get; set; }
    }
}
