//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Historia_clinica_ocupacional
    {
        public int id_his_cli_ocu { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public Nullable<int> id_tipo_exa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string doc_esc_paciente { get; set; }
        public string doc_esc_medico { get; set; }
        public string diagnostico { get; set; }
        public string recomendaciones { get; set; }
        public string ruta { get; set; }
    
        public virtual Tbl_Tipo_examen Tbl_Tipo_examen { get; set; }
        public virtual Tbl_Trabajador Tbl_Trabajador { get; set; }
    }
}
