//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ClaseCiiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ClaseCiiu()
        {
            this.Tbl_Empresa_itemdivision = new HashSet<Tbl_Empresa_itemdivision>();
            this.Tbl_Norma_claseciiu = new HashSet<Tbl_Norma_claseciiu>();
            this.Tbl_Riesgos_item = new HashSet<Tbl_Riesgos_item>();
        }
    
        public int id_clase_ciiu { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual Tbl_GrupoCiiu Tbl_GrupoCiiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Empresa_itemdivision> Tbl_Empresa_itemdivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Norma_claseciiu> Tbl_Norma_claseciiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Riesgos_item> Tbl_Riesgos_item { get; set; }
    }
}
