//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Area()
        {
            this.Tbl_At_it_el_pa = new HashSet<Tbl_At_it_el_pa>();
            this.Tbl_Extintor = new HashSet<Tbl_Extintor>();
            this.Tbl_Puesto_trabajo = new HashSet<Tbl_Puesto_trabajo>();
            this.Tbl_Matriz_Acc_Prev_Corr = new HashSet<Tbl_Matriz_Acc_Prev_Corr>();
        }
    
        public int id_area { get; set; }
        public string nombre { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<long> id_area_padre { get; set; }
        public Nullable<int> nivel { get; set; }
        public string tipo { get; set; }
    
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_At_it_el_pa> Tbl_At_it_el_pa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Extintor> Tbl_Extintor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Puesto_trabajo> Tbl_Puesto_trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Matriz_Acc_Prev_Corr> Tbl_Matriz_Acc_Prev_Corr { get; set; }
    }
}
