//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Plan_trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Plan_trabajo()
        {
            this.Tbl_Obligacion = new HashSet<Tbl_Obligacion>();
        }
    
        public int id_plan_trabajo { get; set; }
        public string nombre { get; set; }
        public string objetivos { get; set; }
        public Nullable<int> anho { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<int> semana_ini { get; set; }
        public Nullable<int> semana_fin { get; set; }
        public Nullable<int> recursos_aprobados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Obligacion> Tbl_Obligacion { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
