//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Alarma
    {
        public int id_alarmas { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string prioridad { get; set; }
        public Nullable<int> id_categorias { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Tbl_Categoria Tbl_Categoria { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
