//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Epp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Epp()
        {
            this.Tbl_Puesto_trabajo_epp = new HashSet<Tbl_Puesto_trabajo_epp>();
            this.Tbl_MatrizEpp = new HashSet<Tbl_MatrizEpp>();
        }
    
        public int id_epp { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_epp { get; set; }
        public string url_imagen { get; set; }
        public string marca_modelo { get; set; }
        public string uso { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string matriz_epp { get; set; }
    
        public virtual Tbl_Empresa Tbl_Empresa { get; set; }
        public virtual Tbl_Tipo_epp Tbl_Tipo_epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Puesto_trabajo_epp> Tbl_Puesto_trabajo_epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MatrizEpp> Tbl_MatrizEpp { get; set; }
    }
}
