//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Evaluacion_riesgo
    {
        public int id_evaluacion_riesgo { get; set; }
        public Nullable<int> id_ide_puesto { get; set; }
        public string control_fuente { get; set; }
        public string control_medio { get; set; }
        public string control_individuo { get; set; }
        public Nullable<System.DateTime> fecha_evaluacion { get; set; }
        public string nombre_responsable { get; set; }
        public string estatus_med_fue { get; set; }
        public string estatus_med_amb { get; set; }
        public string estatus_med_trab { get; set; }
        public Nullable<int> porc_estatus { get; set; }
        public string nivel_deficiencia { get; set; }
        public string interpretacion_deficiencia { get; set; }
        public string nivel_exposicion { get; set; }
        public string interpretacion_exposicion { get; set; }
        public string nivel_probabilidad { get; set; }
        public string interpretacion_probabilidad { get; set; }
        public string nivel_consecuencia { get; set; }
        public string nivel_riesgo { get; set; }
        public string interpretacion_nivel_riesgo { get; set; }
        public string aceptabilidad_riesgo { get; set; }
        public Nullable<int> planta { get; set; }
        public Nullable<int> contratistas { get; set; }
        public Nullable<int> visitantes { get; set; }
        public Nullable<int> total { get; set; }
        public string peor_consecuencia { get; set; }
        public string existencia_requisito_legal { get; set; }
        public string eliminación { get; set; }
        public string sustitución { get; set; }
        public string controles_ingenieria { get; set; }
        public string controles_administrativos { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
    
        public virtual Tbl_Identificacion_puesto Tbl_Identificacion_puesto { get; set; }
    }
}
