//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Perfil_cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Perfil_cargo()
        {
            this.Tbl_Perfil_medico = new HashSet<Tbl_Perfil_medico>();
            this.Tbl_Trabajador = new HashSet<Tbl_Trabajador>();
        }
    
        public int id_perfil_cargo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_cno { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual Tbl_Cno Tbl_Cno { get; set; }
        public virtual Tbl_Empresa Tbl_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Perfil_medico> Tbl_Perfil_medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Trabajador> Tbl_Trabajador { get; set; }
    }
}
