//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Puesto_trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Puesto_trabajo()
        {
            this.Tbl_At_it_el_pa = new HashSet<Tbl_At_it_el_pa>();
            this.Tbl_Identificacion_puesto = new HashSet<Tbl_Identificacion_puesto>();
            this.Tbl_Puesto_trabajo_epp = new HashSet<Tbl_Puesto_trabajo_epp>();
            this.Tbl_Trabajador = new HashSet<Tbl_Trabajador>();
        }
    
        public int id_puesto_trabajo { get; set; }
        public string nombre { get; set; }
        public int id_area { get; set; }
        public string descripcion { get; set; }
        public string recurso_humano { get; set; }
        public string objeto_trabajo { get; set; }
        public string insumos { get; set; }
        public string maquinas { get; set; }
        public string herramientas { get; set; }
        public string emisiones { get; set; }
        public string productos { get; set; }
        public string desechos { get; set; }
        public string foto { get; set; }
    
        public virtual Tbl_Area Tbl_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_At_it_el_pa> Tbl_At_it_el_pa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Identificacion_puesto> Tbl_Identificacion_puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Puesto_trabajo_epp> Tbl_Puesto_trabajo_epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Trabajador> Tbl_Trabajador { get; set; }
    }
}
