//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Simulacro
    {
        public int id_Simulacro { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string UrlArchivo { get; set; }
        public Nullable<int> id_tabla { get; set; }
        public string nombre { get; set; }
    
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
