//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sucursal()
        {
            this.Tbl_Area = new HashSet<Tbl_Area>();
            this.Tbl_Brigada_emergencia = new HashSet<Tbl_Brigada_emergencia>();
            this.Tbl_Documento = new HashSet<Tbl_Documento>();
            this.Tbl_Lista_actividad = new HashSet<Tbl_Lista_actividad>();
            this.Tbl_Matriz_responsabilidad = new HashSet<Tbl_Matriz_responsabilidad>();
            this.Tbl_MatrizEpp = new HashSet<Tbl_MatrizEpp>();
            this.Tbl_Norma_sucursal = new HashSet<Tbl_Norma_sucursal>();
            this.Tbl_Plan = new HashSet<Tbl_Plan>();
            this.Tbl_Simulacro = new HashSet<Tbl_Simulacro>();
            this.Tbl_Tipo_documento = new HashSet<Tbl_Tipo_documento>();
        }
    
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_municpio { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string direccion { get; set; }
        public Nullable<int> sede_principal { get; set; }
        public string representante { get; set; }
        public string movil { get; set; }
        public string fijo { get; set; }
        public Nullable<int> actividad_ppal { get; set; }
        public Nullable<int> actividad_sec { get; set; }
        public Nullable<int> actividad_otra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Area> Tbl_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Brigada_emergencia> Tbl_Brigada_emergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Documento> Tbl_Documento { get; set; }
        public virtual Tbl_Empresa Tbl_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Lista_actividad> Tbl_Lista_actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Matriz_responsabilidad> Tbl_Matriz_responsabilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MatrizEpp> Tbl_MatrizEpp { get; set; }
        public virtual Tbl_Municipio Tbl_Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Norma_sucursal> Tbl_Norma_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Plan> Tbl_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Simulacro> Tbl_Simulacro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Tipo_documento> Tbl_Tipo_documento { get; set; }
    }
}
