//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Trabajador()
        {
            this.Tbl_At_it_el_pa = new HashSet<Tbl_At_it_el_pa>();
            this.Tbl_Desc_socio = new HashSet<Tbl_Desc_socio>();
            this.Tbl_Documento = new HashSet<Tbl_Documento>();
            this.Tbl_Encuesta_politica = new HashSet<Tbl_Encuesta_politica>();
            this.Tbl_Historia_clinica_ocupacional = new HashSet<Tbl_Historia_clinica_ocupacional>();
            this.Tbl_Trabajador_estatus = new HashSet<Tbl_Trabajador_estatus>();
            this.Tbl_Trabajador_gestion = new HashSet<Tbl_Trabajador_gestion>();
            this.Tbl_Usuario = new HashSet<Tbl_Usuario>();
        }
    
        public int id_trabajador { get; set; }
        public string cedula { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string edo_civil { get; set; }
        public string sexo { get; set; }
        public string foto { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_movil { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string direccion { get; set; }
        public int id_municipio { get; set; }
        public int id_puesto_trabajo { get; set; }
        public string es_discapacitado { get; set; }
        public string desc_discapacidad { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<int> id_estatus_actual { get; set; }
        public Nullable<int> id_ccf { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string tipo_vinculacion { get; set; }
        public string codigo_independiente { get; set; }
        public string tipo_horario { get; set; }
        public Nullable<int> id_perfil_cargo { get; set; }
        public Nullable<double> salario { get; set; }
        public string mano_dominante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_At_it_el_pa> Tbl_At_it_el_pa { get; set; }
        public virtual Tbl_Ccf Tbl_Ccf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Desc_socio> Tbl_Desc_socio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Documento> Tbl_Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Encuesta_politica> Tbl_Encuesta_politica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Historia_clinica_ocupacional> Tbl_Historia_clinica_ocupacional { get; set; }
        public virtual Tbl_Municipio Tbl_Municipio { get; set; }
        public virtual Tbl_Perfil_cargo Tbl_Perfil_cargo { get; set; }
        public virtual Tbl_Puesto_trabajo Tbl_Puesto_trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Trabajador_estatus> Tbl_Trabajador_estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Trabajador_gestion> Tbl_Trabajador_gestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Usuario> Tbl_Usuario { get; set; }
    }
}
