//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Identificacion_peligro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Identificacion_peligro()
        {
            this.Tbl_Factor_identificacion = new HashSet<Tbl_Factor_identificacion>();
            this.Tbl_Identificacion_puesto = new HashSet<Tbl_Identificacion_puesto>();
            this.Tbl_Obligacion = new HashSet<Tbl_Obligacion>();
        }
    
        public int id_identificacion_peligro { get; set; }
        public string medidas_control_existentes { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_identificacion { get; set; }
        public Nullable<int> matriz_riesgo { get; set; }
        public string estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Factor_identificacion> Tbl_Factor_identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Identificacion_puesto> Tbl_Identificacion_puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Obligacion> Tbl_Obligacion { get; set; }
    }
}
