//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Evento
    {
        public int id_evento { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_evento { get; set; }
        public string datos_viejos { get; set; }
        public string datos_nuevos { get; set; }
        public string pagina { get; set; }
        public string tabla { get; set; }
    
        public virtual Tbl_Tipo_evento Tbl_Tipo_evento { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
