//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Factor_riesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Factor_riesgo()
        {
            this.Tbl_Factor_identificacion = new HashSet<Tbl_Factor_identificacion>();
            this.Tbl_Riesgos_item = new HashSet<Tbl_Riesgos_item>();
        }
    
        public int id_factor_riesgo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_riesgo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Factor_identificacion> Tbl_Factor_identificacion { get; set; }
        public virtual Tbl_Tipo_riesgo Tbl_Tipo_riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Riesgos_item> Tbl_Riesgos_item { get; set; }
    }
}
