//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Riesgos_item
    {
        public int id_riesgos_item { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_enfermedad_laboral { get; set; }
        public Nullable<int> id_factor_riesgo { get; set; }
    
        public virtual Tbl_ClaseCiiu Tbl_ClaseCiiu { get; set; }
        public virtual Tbl_EnfermedadLaboral Tbl_EnfermedadLaboral { get; set; }
        public virtual Tbl_Factor_riesgo Tbl_Factor_riesgo { get; set; }
    }
}
