//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Desc_socio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Desc_socio()
        {
            this.Tbl_Empleo_anterior = new HashSet<Tbl_Empleo_anterior>();
        }
    
        public int id_desc_socio { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public string lugar_nac { get; set; }
        public string nivel_escolaridad { get; set; }
        public string años_aprob { get; set; }
        public string cabeza_fam { get; set; }
        public string num_hijos { get; set; }
        public string repart_resp { get; set; }
        public string menores_dep { get; set; }
        public string cond_social { get; set; }
        public string mot_despl { get; set; }
        public string tipo_vivienda { get; set; }
        public string serv_pub { get; set; }
        public string sist_seg_soc { get; set; }
        public string reg_afiliacion { get; set; }
        public string nivel_sisben { get; set; }
        public Nullable<int> id_eps { get; set; }
        public string afi_sssp { get; set; }
        public Nullable<int> id_afp { get; set; }
        public string afi_riesgo { get; set; }
        public string estrato { get; set; }
        public string vivienda { get; set; }
        public string industria { get; set; }
        public string ruido { get; set; }
        public string contaminacion { get; set; }
        public string descripcion { get; set; }
    
        public virtual Tbl_Afp Tbl_Afp { get; set; }
        public virtual Tbl_Eps Tbl_Eps { get; set; }
        public virtual Tbl_Trabajador Tbl_Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Empleo_anterior> Tbl_Empleo_anterior { get; set; }
    }
}
