//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AutoEvaluacion
    {
        public int id_Autoevaluacion { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<double> Puntaje { get; set; }
        public Nullable<System.DateTime> AñoPuntaje { get; set; }
    
        public virtual Tbl_Empresa Tbl_Empresa { get; set; }
    }
}
