//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Procedimiento_comunicacion
    {
        public int id_procedimiento { get; set; }
        public Nullable<int> id_brigada { get; set; }
        public string nombre { get; set; }
        public string cargo { get; set; }
        public string num_telefono { get; set; }
        public string llamar { get; set; }
    
        public virtual Tbl_Brigada_emergencia Tbl_Brigada_emergencia { get; set; }
    }
}
