//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorSGSST2017.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trabajador()
        {
            this.acc_inc_lab = new HashSet<acc_inc_lab>();
            this.desc_socio = new HashSet<desc_socio>();
            this.historia_clinica_ocupacional = new HashSet<historia_clinica_ocupacional>();
            this.trabajador_estatus = new HashSet<trabajador_estatus>();
            this.trabajador_gestion = new HashSet<trabajador_gestion>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_trabajador { get; set; }
        public string cedula { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string edo_civil { get; set; }
        public string sexo { get; set; }
        public string foto { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_movil { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string direccion { get; set; }
        public int id_municipio { get; set; }
        public int id_puesto_trabajo { get; set; }
        public string es_discapacitado { get; set; }
        public string desc_discapacidad { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<int> id_estatus_actual { get; set; }
        public Nullable<int> id_ccf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_inc_lab> acc_inc_lab { get; set; }
        public virtual ccf ccf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<desc_socio> desc_socio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historia_clinica_ocupacional> historia_clinica_ocupacional { get; set; }
        public virtual horario horario { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual puesto_trabajo puesto_trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajador_estatus> trabajador_estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajador_gestion> trabajador_gestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
